runtime: go
api_version: go1

handlers:
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
  secure: always
- url: /static/scripts/bootstrap.min.js
  static_files: static/scripts/bootstrap.min.js
  upload: static/scripts/bootstrap.min.js
  secure: always
- url: /static/scripts/jquery-1.12.0.min.js
  static_files: static/scripts/jquery-1.12.0.min.js
  upload: static/scripts/jquery-1.12.0.min.js
  secure: always
- url: /static/scripts/main.js
  static_files: static/scripts/main.js
  upload: static/scripts/main.js
  secure: always
- url: /static/styles/bootstrap.min.css
  static_files: static/styles/bootstrap.min.css
  upload: static/styles/bootstrap.min.css
  secure: always
- url: /static/styles/blog.css
  static_files: static/styles/blog.css
  upload: static/styles/blog.css
  secure: always
- url: /static/images
  static_dir: static/images
- url: /.*
  script: _go_app
  secure: always

nobuild_files: ^(support|articles)/